version: '3.8'

services:
  db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messages
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  messaging-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: messages

volumes:
  postgres_data:
